# Define your apache environment variables here so that 
# you can read them in PHP with $_SERVER['MYVAR']
# Note: quote the value if it contains spaces
SetEnv MYVAR "my value"

# Alternatively you can tell apache to pass the listed 
# native system environment variables to PHP. Your 
# variables have to be defined in compose.yaml and are 
# read in PHP with $_SERVER['MYVAR1'] and $_SERVER['MYVAR2']
#PassEnv MYVAR1 MYVAR2
